### PR TITLE
fix roxygen typo

### PR DESCRIPTION
**Pull request by robertzk**

### CODE REVIEW

**Comment by robertzk** [comment]
Also `compute_align` doesn't exist for me - is it a work in progress?

**Comment by hadley** [comment]
Yeah, it doesn't exist in ggcomp yet.

**Comment by robertzk** [comment]
What about the missing documentation header? (`# @seealso` instead of `#' @seealso`)

**Comment by hadley** [comment]
That was deliberate because `compute_align` doesn't exist

**Pull request closed without merging**
